import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar/Navbar";
import { AuthContextProvider } from "./store/auth-context";
import {
  DashboardContext,
  DashboardContextProvider,
} from "./store/dashboard-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <div className="flex flex-col">
            <Navbar />
            <DashboardContextProvider>{children}</DashboardContextProvider>
          </div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
